### ISSUE TITLE
scene_example CameraUtils plugin

### ISSUE THREAD

**Issue by dford25a** [jsbruglie/gap#40]
Attempting to run scene_example, ubuntu 18.04, gazebo 9.0.0, running spawner.world in gzserver.
Code stalls at line 143 of scene_example.cc ```pub_camera->WaitForConnection();```

**Comment by joao-borrego** [comment]
I have just run the code on my local machine with Ubuntu 16.04 and Gazebo 9.4, in which I cannot replicate the issue.
Have you tried running `gazebo` or `gzserver` with the `--verbose` flag? If so, do you see the debug output generated by [this line](https://github.com/jsbruglie/gap/blob/ff7cf2465ab7b7aa0208b561a8f4b91c77f5bcae/plugins/camera_utils/CameraUtils.cc#L54)? It confirms that indeed the plugin was correctly instanced.
My guess is that the CameraPlugin is not correctly subscribing to the camera requests topic (`~/gap/camera_utils`).

**Comment by dford25a** [comment]
i should have clarified that I was attempting to do this inside a docker container. the --verbose flag did help, i think the root of my problem is that the display can't open inside my container with my current configuration... 

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.2
[Err] [RenderEngine.cc:725] Can't open display:
[Wrn] [RenderEngine.cc:93] Unable to create X window. Rendering will be disabled
[Wrn] [RenderEngine.cc:293] Cannot initialize render engine since render path type is NONE. Ignore this warning ifrendering has been turned off on purpose.
[Msg] [WorldUtils] Loaded world tools.
[Dbg] [WorldUtils.cc:301] [WorldUtils] Physics state 0
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/physics/contacts, deleting message. This warning is printed only once.
[Err] [CameraSensor.cc:112] Unable to create CameraSensor. Rendering is disabled.

**Comment by joao-borrego** [comment]
A few months back, someone in our lab create a docker image with support for Gazebo, ROS and some other software for one of our robots, which may be of help. It is based on [nvidia-docker](https://github.com/NVIDIA/nvidia-docker), and you can find it in [this link](https://github.com/carlos-cardoso/vizzy-docker). 
I'm afraid I have never tried running my code on a docker container myself, but I see no reason as to why it should fail. If you need anything else let me know, otherwise, I'll close the issue :)
