### ISSUE TITLE
Best documentation ever :/

### ISSUE THREAD

**Issue by PirvuCatalin** [jsbruglie/gap#41]
Hi there,

I am just writing this issue to tell you to follow the steps you described in the documentation of this project and also of the tf-shape-detection project. Please try to follow them exactly as you described. I am pretty sure you won't achieve anything.

I am glad that you worked on these awesome projects, but it's so sad that you can't write a proper documentation or atleast some clear usage steps.

Have an awesome day!

**Comment by joao-borrego** [comment]
Hi!

Thank you for your interest in this module. I initially did this work for my MSc thesis a couple years back and haven't really updated it since. The first thing would probably be to port this to a newer Gazebo version and I hope the setup can be greatly simplified. At the time it was a pain to build the dependencies from source and get everything to work out.
I can try to help you with some generic advice, and I think there's a couple of people that managed to work with it fairly recently, so maybe check out recent forks? Regarding the object detection in TF I'm afraid I really can't help out at all as I no longer have access to a CUDA compatible GPU, nor had I set the pipeline up myself in the first place.

Finally, don't let this discourage you and your research! I know it can be tough at times: you find some software here on GitHub you'd like to try out, just to find that it's not regularly maintained and documentation is scarce or outdated. And while I'd like to keep this up to date and helpful for other people, I'm now working on something else entirely, and am no longer devoting much time to these tools.

Cheers

**Comment by PirvuCatalin** [comment]
I'll look into forking this one, I'm pretty sure it will work with the old dependecies and without a cuda GPU, but with some better steps :).
